Adding github workflows
great-expectations/jsonforms-antd-renderers pull request #11
Opened 2024-02-29 00:53 UTC by TrangPham

Tested on my fork: https://github.com/TrangPham/jsonforms-antd-renderers/actions/runs/8089417491/job/22105275009

2024-02-29 01:33 UTC, DrewHoo requested changes

2024-02-29 01:33 UTC, DrewHoo commented on .github/workflows/tests.yaml
> +          node-version: 18
There's a way to reference the version specified in the .nvmrc--see mercury-web's deploy or validate workflows for an example of the exact syntax

2024-02-29 01:33 UTC, DrewHoo commented on .github/workflows/tests.yaml
> +            ${{ runner.os }}-pnpm-store-
Trailing dash here seems odd

2024-02-29 01:33 UTC, DrewHoo commented on .github/workflows/tests.yaml
> +        run: pnpm install
Does this use the lockfile by default or do you need to specify frozen-lockfile?

2024-02-29 14:57 UTC, NathanFarmer reviewed
Are we planning to use the pre-commit stage? Was that added to our entire great-expectations organization or did we add that?

2024-02-29 15:41 UTC, Kilo59 commented
Just opened a quick PR with some minimal pre-commit config settings
https://github.com/great-expectations/jsonforms-antd-renderers/pull/15

2024-02-29 20:47 UTC, DrewHoo commented on .github/workflows/tests.yaml
> +          node-version: 18
https://github.com/greatexpectationslabs/mercury-web/blob/main/.github/actions/setup-node/action.yml

2024-03-01 21:57 UTC, DrewHoo approved these changes

2024-03-01 21:57 UTC, DrewHoo commented on .github/workflows/tests.yaml
> +      - main
I don't think this is an issue but want to double check: if joe schmoe opens a PR against this repo, can they do stuff like make changes to this workflow that logs api keys or anything like that? I'm pretty sure the answer is no

2024-03-01 21:57 UTC, merged