feat: Implement DatetimeControl and add tests
great-expectations/jsonforms-antd-renderers pull request #24
Opened 2024-03-06 20:23 UTC by TrangPham

2024-03-06 21:03 UTC, NathanFarmer requested changes
Can you please add the `required` asterisk?

2024-03-06 21:03 UTC, NathanFarmer commented on src/controls/DatetimeControl.tsx
> +    <Form.Item label={label} id={id} name={path}>
You can pass `required` here.

2024-03-20 23:33 UTC, DrewHoo commented on package.json
> +    "rc-picker": "^4.2.0",
these should be normal dependencies, right?

2024-03-20 23:37 UTC, DrewHoo requested changes
G2G if you change peer dependencies to regular dependencies--locale configurability can wait TBH

2024-03-20 23:37 UTC, DrewHoo commented on src/controls/DatetimeControl.tsx
> +  const dateFormat = "MM/DD/YYYY"
Can you make this configurable via UISchema or jsonschema / use browser-detected locale as a default?

2024-04-12 20:55 UTC, DrewHoo commented
> @DrewHoo Looks like I need your review on it too since you previously requested changes.

Looks like dependencies still aren't updated? Also the DateControlOptions ought to be differentiated instead of added to a union with TextControlOptions. Something like this might work:
```
type JsonSchemaTypeToControlOptions<
  T,
> = T extends { type: infer U; format?: infer V }
? U extends "object" 
    ? unknown
    : U extends "string"
      ?  V extends "date" ? DateControlOptions : TextControlOptions
      : ...
```

2024-11-02 15:32 UTC, DrewHoo commented
> @DrewHoo Is this no longer required? If not we can close this PR

Yeah I think so!

2024-11-02 17:52 UTC, closed without merging