feat: Anyof and Storybook GH Pages
great-expectations/jsonforms-antd-renderers pull request #56
Opened 2024-03-22 16:27 UTC by TrangPham

2024-03-22 16:30 UTC, DrewHoo commented on src/controls/combinators/OneOfControl.tsx
> +        labeledElements={combinatorSchemaSwitcher}
What problem does pushing CombinatorSchemaSwitcher into Control label solve?

2024-03-25 17:24 UTC, NathanFarmer requested changes

2024-03-25 17:24 UTC, NathanFarmer commented on .github/workflows/publish-storybook.yml
> +            ${{ runner.os }}-pnpm-store-
Does this cache dependencies between runs of this workflow?

2024-03-25 17:24 UTC, NathanFarmer commented on src/controls/combinators/AnyOfControl.test.tsx
> +  test("OneOf Control persists state when switching between subschemas", async () => {
Typo in "OneOf" instead of "AnyOf".

2024-03-25 17:24 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +      description: "this is a minimal oneOf combinator schema",
Typo "oneOf" instead of "anyOf".

2024-03-25 17:24 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +      description: "this is a minimal oneOf combinator schema",
Typo "oneOf" instead of "anyOf".

2024-03-25 17:24 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +      description: "this is a minimal oneOf combinator schema",
Typo "oneOf" instead of "anyOf".

2024-03-25 17:24 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +      description: "this is a minimal oneOf combinator schema",
Typo "oneOf" instead of "anyOf".

2024-03-25 17:24 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +          options: { optionType: "button" } satisfies OneOfControlOptions,
Shouldn't this be `AnyOfControlOptions`? Not sure if you added that type.

2024-03-25 17:24 UTC, NathanFarmer commented on src/testSchemas/anyOfSchema.ts
> +    // console.log("SplitterUISchema Tester", { rank, schema, schemaPath, path })
Console log

2024-03-25 18:45 UTC, NathanFarmer commented on src/stories/controls/AnyOfControl.stories.tsx
> +          options: { optionType: "button" } satisfies OneOfControlOptions,
Maybe add a new type alias for now?

2024-03-26 13:38 UTC, NathanFarmer approved these changes
Thanks for this!!

2024-03-26 18:34 UTC, merged