add ColumnLayoutProps to ControlUISchema
great-expectations/jsonforms-antd-renderers pull request #94
Opened 2024-09-13 21:22 UTC by shiplet

We need the column spacing to be a bit more flexible in horizontal layouts.

This introduces a `ColumnLayoutProps` and `layoutProps` interface that allows for the specification of column widths on individual HorizontalLayout elements.

2024-09-13 22:37 UTC, NathanFarmer requested changes
It's hard to wrap my mind around how this works. Can you add a story to [HorizontalLayout.stories.tsx](https://github.com/great-expectations/jsonforms-antd-renderers/blob/main/src/stories/layouts/HorizontalLayout.stories.tsx)?

2024-09-16 15:45 UTC, shiplet commented
@NathanFarmer It's really more of a change to the Control definition, so I added an "empty" `layoutProps` to each of our Control UISchemas in the stories. I also attached screenshots to the initial PR description showing it in use as well.

2024-09-16 17:11 UTC, NathanFarmer reviewed
How does this work with multiple columns? That's what I wasn't quite understanding and was expecting to see in the story.

Also, is `layoutProps: { columns: undefined }` now required, or did you add them everywhere to make it clear that it's an available prop? If it's required, I would think that it's a breaking change.

Do you intend for this PR to trigger release? If so your PR title should follow conventional commit syntax.

2024-09-16 17:11 UTC, NathanFarmer commented on package.json
> -    "test:cov": "vitest run --coverage --reporter=junit --outputFile=./junit.xml",
What does this do?

2024-09-16 17:21 UTC, NathanFarmer approved these changes
Approved based on synchronous conversation

2024-09-16 17:23 UTC, merged